<a href="https://colab.research.google.com/github/Strix9289/Introduction-of-Machine-Learning/blob/master/statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 統計

In [1]:
import numpy as np
import scipy as sns
import matplotlib.pyplot as plt
import pandas as pd

## ベルヌーイ分布

ベルヌーイ分布とは、「当たりが出る確率が$p$のくじを1回引いたときの当たり回数」に従う確率分布

In [ ]:
# 小数第3位まで表示
%precision 3

'%.3f'

In [ ]:
import numpy as np
data = np.array([9,1,2,4,7,5,3])
# 積み上げ
print('Cum:', data.cumsum())

Cum: [ 9 10 12 16 23 28 31]


In [ ]:
import numpy.random as random

| 機能 | 意味 |
|:---------|:-------|
| `rand` | 一様分布。0.0以上、1.0未満 |
| `random_sample` | 一様分布。0.0以上、1.0未満（`rand`とは引数の指定方法が異なる） |
| `randint` | 一様分布。任意の範囲の整数 |
| `randn` | 正規分布。平均0、標準偏差1の乱数 |
| `normal` | 正規分布。任意の平均、標準偏差の乱数 |
| `binomial` | 二項分布の乱数 |
| `beta` | ベータ分布の乱数 |
| `gamma` | ガンマ分布の乱数 |
| `chisquare` | カイ二乗分布の乱数 |

In [ ]:

# 抽出対象データ
data = np.array([9,2,3,4,10,6,7,8,1,5])

# ランダム抽出
# 10個を抽出（重複あり、復元抽出）
print(random.choice(data, 10))
# 10個を抽出（重複なし、非復元抽出)
print(random.choice(data, 10, replace = False)) 

[2 1 3 2 3 9 3 4 5 8]
[ 7  1  9  5 10  4  6  3  8  2]


In [ ]:
%timeit #処理

In [ ]:
# データの準備
array1 = np.arange(9).reshape(3,3)
print(array1)

In [ ]:
array2 = np.arange(9,18).reshape(3,3)
print(array2)

In [ ]:
# 行列の積
np.dot(array1, array2)

In [ ]:
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


統計学の使う知識

|変数|説明|
|:---|:---|
|mean|平均|
|median|中央値|
|mode|最頻値|
|var|分散|
|std|標準偏差|
|cov(x,y)|xとyの共分散|




sp.stats.pearsonr(x1, x2) >>> r, p
r: 相関係数
p: p値
